[custom]
;规则从上往下匹配，优先命中上位规则

;美国账户 / T-Mobile / PayPal / 身份类账号
ruleset=🇺🇸 美国账户,[]DOMAIN-SUFFIX,t-mobile.com
ruleset=🇺🇸 美国账户,[]DOMAIN-SUFFIX,tmobile.com
ruleset=🇺🇸 美国账户,[]DOMAIN-SUFFIX,t-mobilemoney.com
ruleset=🇺🇸 美国账户,[]DOMAIN-SUFFIX,sprint.com
ruleset=🇺🇸 美国账户,[]GEOSITE,paypal

;AI服务
ruleset=🤖 AI服务,https://raw.githubusercontent.com/rule2c/Customized_Rules/refs/heads/main/rule/Chat-AI.list
ruleset=🤖 AI服务,[]GEOSITE,openai
ruleset=🤖 AI服务,[]GEOSITE,category-ai-!cn

;谷歌/流媒体/TikTok
ruleset=🎯 全球直连,[]GEOSITE,google-cn
ruleset=🇬 谷歌服务,[]GEOSITE,google
ruleset=🇬 谷歌服务,[]GEOIP,google,no-resolve
ruleset=🎥 流媒体,[]GEOSITE,netflix
ruleset=🎥 流媒体,[]GEOSITE,disney
ruleset=🎥 流媒体,[]GEOSITE,hbo
ruleset=🎥 流媒体,[]GEOSITE,primevideo
ruleset=🎶 TikTok,[]GEOSITE,tiktok

;本地地址和域名直连
ruleset=🎯 全球直连,[]GEOSITE,private
ruleset=🎯 全球直连,[]GEOIP,private,no-resolve
ruleset=🎯 全球直连,https://raw.githubusercontent.com/rule2c/Customized_Rules/refs/heads/main/rule/Custom_Direct_Classical.list

;自定义代理
ruleset=🚀 手动选择,https://raw.githubusercontent.com/rule2c/Customized_Rules/refs/heads/main/rule/Custom_Proxy_Classical.list

;国内服务直连
#ruleset=🎯 全球直连,[]GEOSITE,google-cn
ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
ruleset=🎯 全球直连,https://raw.githubusercontent.com/rule2c/Customized_Rules/refs/heads/main/rule/Steam_CDN.list
ruleset=🎯 全球直连,[]GEOSITE,category-game-platforms-download
ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker

;常规分流
#ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=💬 即时通讯,[]GEOSITE,category-communication
ruleset=🌐 社交媒体,[]GEOSITE,category-social-media-!cn
ruleset=🚀 GitHub,[]GEOSITE,github
ruleset=Ⓜ️ 微软服务,[]GEOSITE,microsoft
ruleset=🍎 苹果服务,[]GEOSITE,apple
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=🎮 游戏平台,[]GEOSITE,category-games
ruleset=📢 谷歌FCM,[]GEOSITE,googlefcm
ruleset=💬 即时通讯,[]GEOIP,telegram,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,twitter,no-resolve
ruleset=🌐 社交媒体,[]GEOIP,facebook,no-resolve
ruleset=🚀 测速工具,[]GEOSITE,category-speedtest

;GFW / 国内 / 兜底
ruleset=🚀 手动选择,[]GEOSITE,gfw
#ruleset=🎯 全球直连,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOSITE,cn
ruleset=🎯 全球直连,[]GEOIP,cn,no-resolve
ruleset=🔀 非标端口,clash-classic:https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml,28800
ruleset=🐟 漏网之鱼,[]FINAL

;设置分组标志位
custom_proxy_group=🚀 手动选择`select`.*`[]🎯 全球直连

custom_proxy_group=🇺🇸 美国住宅`select`.*NoSLA-LAX_sb-xtls-reality.*

#custom_proxy_group=💳 PayPal`select`[]🇺🇸 美国住宅
custom_proxy_group=🇺🇸 美国账户`select`[]🇺🇸 美国住宅

custom_proxy_group=🎥 流媒体`select`[]🇺🇸 美国住宅
custom_proxy_group=🎶 TikTok`select`[]🇺🇸 美国住宅

custom_proxy_group=🤖 AI服务`select`[]🚀 手动选择

custom_proxy_group=💬 即时通讯`select`[]🚀 手动选择`[]🎯 全球直连`.*
custom_proxy_group=🌐 社交媒体`select`[]🚀 手动选择`[]🎯 全球直连`.*
custom_proxy_group=🚀 GitHub`select`[]🚀 手动选择`[]🎯 全球直连`.*
#custom_proxy_group=Ⓜ️ 微软Bing`select`[]🚀 手动选择`[]🎯 全球直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 手动选择`[]🎯 全球直连`.*
custom_proxy_group=🇬 谷歌服务`select`[]🚀 手动选择`[]🎯 全球直连`.*
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 手动选择`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 手动选择`.*
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🚀 手动选择`.*
custom_proxy_group=🎮 Steam`select`[]🎯 全球直连`[]🚀 手动选择`.*
custom_proxy_group=🚀 测速工具`select`[]🎯 全球直连`[]🚀 手动选择`.*

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 手动选择`[]🎯 全球直连`.*
custom_proxy_group=🔀 非标端口`select`[]🐟 漏网之鱼`[]🎯 全球直连`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT
;设置分组标志位结束

enable_rule_generator=true
overwrite_original_rules=true
